
%define MAX_INPUT_LENGTH 65536
    
%include './lib/asm_macros.asm'
    
section .text
    global _start
    
_start:
    mov esi, 0
    call premalloc
    call _read_file_argument
    call _read_file
    push ebp
    mov ebp, esp
    call LISP
    pop ebp
    mov edi, outbuff
    call print_mm32
    mov eax, 1
    mov ebx, 0
    int 0x80
    
LISP:
    push ebp
    mov ebp, esp
    push esi
    section .data
    cmp byte [eswitch], 1
    jne LOOP_0
    cmp byte [backtrack_switch], 1
    je LA1
    jmp terminate_program
LOOP_0:
    used_arg_count dd 0
    push_prefix db 'push dword [ebp', 0x00
    push_prefix_global db 'push dword [', 0x00
    fn_arg_num dd 0
    cmp byte [eswitch], 1
    jne LOOP_1
    cmp byte [backtrack_switch], 1
    je LA1
    jmp terminate_program
LOOP_1:
    is_global db 1
    loop_counter dd 0
    section .bss
    push_buffer resb 128
    symbol_table resb 262144
    section .text
    error_store 'PREAMBLE'
    call vstack_clear
    call PREAMBLE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_2
    cmp byte [backtrack_switch], 1
    je LA1
    jmp terminate_program
LOOP_2:
    
LA2:
    error_store 'ROOT_BODY'
    call vstack_clear
    call ROOT_BODY
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA3
    
LA3:
    
LA4:
    cmp byte [eswitch], 0
    je LA2
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_3
    cmp byte [backtrack_switch], 1
    je LA1
    jmp terminate_program
LOOP_3:
    error_store 'POSTAMBLE'
    call vstack_clear
    call POSTAMBLE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_4
    cmp byte [backtrack_switch], 1
    je LA1
    jmp terminate_program
LOOP_4:
    
LA1:
    
LA5:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
ROOT_BODY:
    push ebp
    mov ebp, esp
    push esi
    error_store 'COMMENT'
    call vstack_clear
    call COMMENT
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA6
    
LA6:
    cmp byte [eswitch], 0
    je LA7
    test_input_string "["
    cmp byte [eswitch], 1
    je LA8
    print "; starting ROOT_BODY"
    print 0x0A
    print '    '
    error_store 'DEFUNC'
    call vstack_clear
    call DEFUNC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA9
    print "; generated by DEFUNC"
    print 0x0A
    print '    '
    
LA9:
    
LA10:
    cmp byte [eswitch], 1
    je LA11
    
LA11:
    cmp byte [eswitch], 0
    je LA12
    error_store 'DEFINE'
    call vstack_clear
    call DEFINE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA13
    print "; generated by DEFINE"
    print 0x0A
    print '    '
    
LA13:
    
LA14:
    cmp byte [eswitch], 1
    je LA15
    
LA15:
    cmp byte [eswitch], 0
    je LA12
    error_store 'SET'
    call vstack_clear
    call SET
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA16
    print "; generated by SET"
    print 0x0A
    print '    '
    
LA16:
    
LA17:
    cmp byte [eswitch], 1
    je LA18
    
LA18:
    cmp byte [eswitch], 0
    je LA12
    error_store 'ASMMACRO'
    call vstack_clear
    call ASMMACRO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA19
    print "; generated by ASMMACRO"
    print 0x0A
    print '    '
    
LA19:
    
LA20:
    cmp byte [eswitch], 1
    je LA21
    
LA21:
    cmp byte [eswitch], 0
    je LA12
    error_store 'WHILE'
    call vstack_clear
    call WHILE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA22
    print "; generated by WHILE"
    print 0x0A
    print '    '
    
LA22:
    
LA23:
    cmp byte [eswitch], 1
    je LA24
    
LA24:
    cmp byte [eswitch], 0
    je LA12
    error_store 'IF_ELSE'
    call vstack_clear
    call IF_ELSE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA25
    print "; generated by IF_ELSE"
    print 0x0A
    print '    '
    
LA25:
    
LA26:
    cmp byte [eswitch], 1
    je LA27
    
LA27:
    cmp byte [eswitch], 0
    je LA12
    error_store 'IF'
    call vstack_clear
    call IF
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA28
    print "; generated by IF"
    print 0x0A
    print '    '
    
LA28:
    
LA29:
    cmp byte [eswitch], 1
    je LA30
    
LA30:
    cmp byte [eswitch], 0
    je LA12
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA31
    print "; generated by ARITHMETIC"
    print 0x0A
    print '    '
    
LA31:
    
LA32:
    cmp byte [eswitch], 1
    je LA33
    
LA33:
    cmp byte [eswitch], 0
    je LA12
    error_store 'ASM'
    call vstack_clear
    call ASM
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA34
    print "; generated by ASM"
    print 0x0A
    print '    '
    
LA34:
    
LA35:
    cmp byte [eswitch], 1
    je LA36
    
LA36:
    cmp byte [eswitch], 0
    je LA12
    error_store 'MOV'
    call vstack_clear
    call MOV
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA37
    print "; generated by MOV"
    print 0x0A
    print '    '
    
LA37:
    
LA38:
    cmp byte [eswitch], 1
    je LA39
    
LA39:
    cmp byte [eswitch], 0
    je LA12
    error_store 'BUILTINS'
    call vstack_clear
    call BUILTINS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA40
    print "; generated by BUILTINS"
    print 0x0A
    print '    '
    
LA40:
    
LA41:
    cmp byte [eswitch], 1
    je LA42
    
LA42:
    cmp byte [eswitch], 0
    je LA12
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA43
    print "; generated by FUNC_CALL"
    print 0x0A
    print '    '
    
LA43:
    
LA44:
    cmp byte [eswitch], 1
    je LA45
    
LA45:
    
LA12:
    cmp byte [eswitch], 1
    jne LOOP_5
    cmp byte [backtrack_switch], 1
    je LA8
    jmp terminate_program
LOOP_5:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_6
    cmp byte [backtrack_switch], 1
    je LA8
    jmp terminate_program
LOOP_6:
    
LA8:
    
LA7:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
PREAMBLE:
    push ebp
    mov ebp, esp
    push esi
    call label
    print "section .text"
    print 0x0A
    print '    '
    print "global _start"
    print 0x0A
    print '    '
    call label
    print "_start:"
    print 0x0A
    print '    '
    print "push ebp"
    print 0x0A
    print '    '
    print "mov ebp, esp"
    print 0x0A
    print '    '
    
LA46:
    
LA47:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
POSTAMBLE:
    push ebp
    mov ebp, esp
    push esi
    print "mov esp, ebp"
    print 0x0A
    print '    '
    print "pop ebp"
    print 0x0A
    print '    '
    print "mov ebx, eax"
    print 0x0A
    print '    '
    print "mov eax, 1"
    print 0x0A
    print '    '
    print "int 0x80"
    print 0x0A
    print '    '
    
LA48:
    
LA49:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
BODY:
    push ebp
    mov ebp, esp
    push esi
    error_store 'COMMENT'
    call vstack_clear
    call COMMENT
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA50
    
LA50:
    cmp byte [eswitch], 0
    je LA51
    test_input_string "["
    cmp byte [eswitch], 1
    je LA52
    print "; starting BODY"
    print 0x0A
    print '    '
    error_store 'DEFINE'
    call vstack_clear
    call DEFINE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA53
    print "; generated by DEFINE"
    print 0x0A
    print '    '
    
LA53:
    
LA54:
    cmp byte [eswitch], 1
    je LA55
    
LA55:
    cmp byte [eswitch], 0
    je LA56
    error_store 'SET'
    call vstack_clear
    call SET
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA57
    print "; generated by SET"
    print 0x0A
    print '    '
    
LA57:
    
LA58:
    cmp byte [eswitch], 1
    je LA59
    
LA59:
    cmp byte [eswitch], 0
    je LA56
    error_store 'WHILE'
    call vstack_clear
    call WHILE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA60
    print "; generated by WHILE"
    print 0x0A
    print '    '
    
LA60:
    
LA61:
    cmp byte [eswitch], 1
    je LA62
    
LA62:
    cmp byte [eswitch], 0
    je LA56
    error_store 'IF_ELSE'
    call vstack_clear
    call IF_ELSE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA63
    print "; generated by IF_ELSE"
    print 0x0A
    print '    '
    
LA63:
    
LA64:
    cmp byte [eswitch], 1
    je LA65
    
LA65:
    cmp byte [eswitch], 0
    je LA56
    error_store 'IF'
    call vstack_clear
    call IF
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA66
    print "; generated by IF"
    print 0x0A
    print '    '
    
LA66:
    
LA67:
    cmp byte [eswitch], 1
    je LA68
    
LA68:
    cmp byte [eswitch], 0
    je LA56
    error_store 'CONTINUE'
    call vstack_clear
    call CONTINUE
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA69
    print "; generated by CONTINUE"
    print 0x0A
    print '    '
    
LA69:
    
LA70:
    cmp byte [eswitch], 1
    je LA71
    
LA71:
    cmp byte [eswitch], 0
    je LA56
    error_store 'BREAK'
    call vstack_clear
    call BREAK
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA72
    print "; generated by BREAK"
    print 0x0A
    print '    '
    
LA72:
    
LA73:
    cmp byte [eswitch], 1
    je LA74
    
LA74:
    cmp byte [eswitch], 0
    je LA56
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA75
    print "; generated by ARITHMETIC"
    print 0x0A
    print '    '
    
LA75:
    
LA76:
    cmp byte [eswitch], 1
    je LA77
    
LA77:
    cmp byte [eswitch], 0
    je LA56
    error_store 'ASM'
    call vstack_clear
    call ASM
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA78
    print "; generated by ASM"
    print 0x0A
    print '    '
    
LA78:
    
LA79:
    cmp byte [eswitch], 1
    je LA80
    
LA80:
    cmp byte [eswitch], 0
    je LA56
    error_store 'MOV'
    call vstack_clear
    call MOV
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA81
    print "; generated by MOV"
    print 0x0A
    print '    '
    
LA81:
    
LA82:
    cmp byte [eswitch], 1
    je LA83
    
LA83:
    cmp byte [eswitch], 0
    je LA56
    error_store 'BUILTINS'
    call vstack_clear
    call BUILTINS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA84
    print "; generated by BUILTINS"
    print 0x0A
    print '    '
    
LA84:
    
LA85:
    cmp byte [eswitch], 1
    je LA86
    
LA86:
    cmp byte [eswitch], 0
    je LA56
    error_store 'RETURN'
    call vstack_clear
    call RETURN
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA87
    print "; generated by RETURN"
    print 0x0A
    print '    '
    
LA87:
    
LA88:
    cmp byte [eswitch], 1
    je LA89
    
LA89:
    cmp byte [eswitch], 0
    je LA56
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA90
    print "; generated by FUNC_CALL"
    print 0x0A
    print '    '
    
LA90:
    
LA91:
    cmp byte [eswitch], 1
    je LA92
    
LA92:
    cmp byte [eswitch], 0
    je LA56
    error_store 'BODY'
    call vstack_clear
    call BODY
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA93
    print "; generated by BODY"
    print 0x0A
    print '    '
    
LA93:
    
LA94:
    cmp byte [eswitch], 1
    je LA95
    
LA95:
    
LA56:
    cmp byte [eswitch], 1
    jne LOOP_7
    cmp byte [backtrack_switch], 1
    je LA52
    jmp terminate_program
LOOP_7:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_8
    cmp byte [backtrack_switch], 1
    je LA52
    jmp terminate_program
LOOP_8:
    
LA52:
    
LA51:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
CONTINUE:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "continue"
    cmp byte [eswitch], 1
    je LA96
    print "jmp "
    call gn2
    print 0x0A
    print '    '
    
LA96:
    
LA97:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
BREAK:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "break"
    cmp byte [eswitch], 1
    je LA98
    print "jmp "
    call gn1
    print 0x0A
    print '    '
    
LA98:
    
LA99:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
ARITHMETIC:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "+"
    cmp byte [eswitch], 1
    je LA100
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_9
    cmp byte [backtrack_switch], 1
    je LA100
    jmp terminate_program
LOOP_9:
    print "add eax, ebx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA100:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "-"
    cmp byte [eswitch], 1
    je LA102
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_10
    cmp byte [backtrack_switch], 1
    je LA102
    jmp terminate_program
LOOP_10:
    print "sub eax, ebx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA102:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "*"
    cmp byte [eswitch], 1
    je LA103
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_11
    cmp byte [backtrack_switch], 1
    je LA103
    jmp terminate_program
LOOP_11:
    print "imul eax, ebx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA103:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "/"
    cmp byte [eswitch], 1
    je LA104
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_12
    cmp byte [backtrack_switch], 1
    je LA104
    jmp terminate_program
LOOP_12:
    print "xor edx, edx"
    print 0x0A
    print '    '
    print "div ebx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    cmp byte [eswitch], 1
    jne LOOP_13
    cmp byte [backtrack_switch], 1
    je LA104
    jmp terminate_program
LOOP_13:
    
LA104:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "%"
    cmp byte [eswitch], 1
    je LA105
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_14
    cmp byte [backtrack_switch], 1
    je LA105
    jmp terminate_program
LOOP_14:
    print "xor edx, edx"
    print 0x0A
    print '    '
    print "div ebx"
    print 0x0A
    print '    '
    print "mov eax, edx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA105:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "and"
    cmp byte [eswitch], 1
    je LA106
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_15
    cmp byte [backtrack_switch], 1
    je LA106
    jmp terminate_program
LOOP_15:
    print "and eax, ebx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA106:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "or"
    cmp byte [eswitch], 1
    je LA107
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_16
    cmp byte [backtrack_switch], 1
    je LA107
    jmp terminate_program
LOOP_16:
    print "or eax, ebx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA107:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "not"
    cmp byte [eswitch], 1
    je LA108
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_17
    cmp byte [backtrack_switch], 1
    je LA108
    jmp terminate_program
LOOP_17:
    print "not eax"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA108:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "<="
    cmp byte [eswitch], 1
    je LA109
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_18
    cmp byte [backtrack_switch], 1
    je LA109
    jmp terminate_program
LOOP_18:
    print "cmp eax, ebx"
    print 0x0A
    print '    '
    print "mov eax, 0"
    print 0x0A
    print '    '
    print "setle al"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA109:
    cmp byte [eswitch], 0
    je LA101
    test_input_string ">="
    cmp byte [eswitch], 1
    je LA110
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_19
    cmp byte [backtrack_switch], 1
    je LA110
    jmp terminate_program
LOOP_19:
    print "cmp eax, ebx"
    print 0x0A
    print '    '
    print "mov eax, 0"
    print 0x0A
    print '    '
    print "setge al"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA110:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "=="
    cmp byte [eswitch], 1
    je LA111
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_20
    cmp byte [backtrack_switch], 1
    je LA111
    jmp terminate_program
LOOP_20:
    print "cmp eax, ebx"
    print 0x0A
    print '    '
    print "mov eax, 0"
    print 0x0A
    print '    '
    print "sete al"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA111:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "!="
    cmp byte [eswitch], 1
    je LA112
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_21
    cmp byte [backtrack_switch], 1
    je LA112
    jmp terminate_program
LOOP_21:
    print "cmp eax, ebx"
    print 0x0A
    print '    '
    print "mov eax, 0"
    print 0x0A
    print '    '
    print "setne al"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    cmp byte [eswitch], 1
    jne LOOP_22
    cmp byte [backtrack_switch], 1
    je LA112
    jmp terminate_program
LOOP_22:
    
LA112:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "<<"
    cmp byte [eswitch], 1
    je LA113
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_23
    cmp byte [backtrack_switch], 1
    je LA113
    jmp terminate_program
LOOP_23:
    print "mov ecx, ebx"
    print 0x0A
    print '    '
    print "shl eax, cl"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    cmp byte [eswitch], 1
    jne LOOP_24
    cmp byte [backtrack_switch], 1
    je LA113
    jmp terminate_program
LOOP_24:
    
LA113:
    cmp byte [eswitch], 0
    je LA101
    test_input_string ">>"
    cmp byte [eswitch], 1
    je LA114
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_25
    cmp byte [backtrack_switch], 1
    je LA114
    jmp terminate_program
LOOP_25:
    print "mov ecx, ebx"
    print 0x0A
    print '    '
    print "shr eax, cl"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    cmp byte [eswitch], 1
    jne LOOP_26
    cmp byte [backtrack_switch], 1
    je LA114
    jmp terminate_program
LOOP_26:
    
LA114:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "^"
    cmp byte [eswitch], 1
    je LA115
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_27
    cmp byte [backtrack_switch], 1
    je LA115
    jmp terminate_program
LOOP_27:
    print "xor eax, ebx"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA115:
    cmp byte [eswitch], 0
    je LA101
    test_input_string "<"
    cmp byte [eswitch], 1
    je LA116
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_28
    cmp byte [backtrack_switch], 1
    je LA116
    jmp terminate_program
LOOP_28:
    print "cmp eax, ebx"
    print 0x0A
    print '    '
    print "mov eax, 0"
    print 0x0A
    print '    '
    print "setl al"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA116:
    cmp byte [eswitch], 0
    je LA101
    test_input_string ">"
    cmp byte [eswitch], 1
    je LA117
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_29
    cmp byte [backtrack_switch], 1
    je LA117
    jmp terminate_program
LOOP_29:
    print "cmp eax, ebx"
    print 0x0A
    print '    '
    print "mov eax, 0"
    print 0x0A
    print '    '
    print "setg al"
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA117:
    
LA101:
    cmp byte [eswitch], 1
    je LA118
    
LA118:
    
LA119:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
RETURN:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "return"
    cmp byte [eswitch], 1
    je LA120
    error_store 'BINOP_ARGS'
    call vstack_clear
    call BINOP_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_30
    cmp byte [backtrack_switch], 1
    je LA120
    jmp terminate_program
LOOP_30:
    print "mov esp, ebp"
    print 0x0A
    print '    '
    print "pop ebp"
    print 0x0A
    print '    '
    print "ret"
    print 0x0A
    print '    '
    
LA120:
    
LA121:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
WHILE:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "while"
    cmp byte [eswitch], 1
    je LA122
    test_input_string "["
    cmp byte [eswitch], 1
    jne LOOP_31
    cmp byte [backtrack_switch], 1
    je LA122
    jmp terminate_program
LOOP_31:
    call label
    call gn2
    print ":"
    print 0x0A
    print '    '
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA123
    
LA123:
    cmp byte [eswitch], 0
    je LA124
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA125
    
LA125:
    
LA124:
    cmp byte [eswitch], 1
    jne LOOP_32
    cmp byte [backtrack_switch], 1
    je LA122
    jmp terminate_program
LOOP_32:
    print "cmp eax, 1"
    print 0x0A
    print '    '
    print "jne "
    call gn1
    print 0x0A
    print '    '
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_33
    cmp byte [backtrack_switch], 1
    je LA122
    jmp terminate_program
LOOP_33:
    
LA126:
    error_store 'BODY'
    call vstack_clear
    call BODY
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA127
    
LA127:
    
LA128:
    cmp byte [eswitch], 0
    je LA126
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_34
    cmp byte [backtrack_switch], 1
    je LA122
    jmp terminate_program
LOOP_34:
    print "jmp "
    call gn2
    print 0x0A
    print '    '
    call label
    call gn1
    print ":"
    print 0x0A
    print '    '
    
LA122:
    
LA129:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
IF:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "if"
    cmp byte [eswitch], 1
    je LA130
    test_input_string "["
    cmp byte [eswitch], 1
    jne LOOP_35
    cmp byte [backtrack_switch], 1
    je LA130
    jmp terminate_program
LOOP_35:
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA131
    
LA131:
    cmp byte [eswitch], 0
    je LA132
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA133
    
LA133:
    
LA132:
    cmp byte [eswitch], 1
    jne LOOP_36
    cmp byte [backtrack_switch], 1
    je LA130
    jmp terminate_program
LOOP_36:
    print "cmp eax, 1"
    print 0x0A
    print '    '
    print "jne "
    call gn1
    print 0x0A
    print '    '
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_37
    cmp byte [backtrack_switch], 1
    je LA130
    jmp terminate_program
LOOP_37:
    
LA134:
    error_store 'BODY'
    call vstack_clear
    call BODY
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 0
    je LA134
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_38
    cmp byte [backtrack_switch], 1
    je LA130
    jmp terminate_program
LOOP_38:
    call label
    call gn1
    print ":"
    print 0x0A
    print '    '
    
LA130:
    
LA135:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
IF_ELSE:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "if/else"
    cmp byte [eswitch], 1
    je LA136
    test_input_string "["
    cmp byte [eswitch], 1
    jne LOOP_39
    cmp byte [backtrack_switch], 1
    je LA136
    jmp terminate_program
LOOP_39:
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA137
    
LA137:
    cmp byte [eswitch], 0
    je LA138
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA139
    
LA139:
    
LA138:
    cmp byte [eswitch], 1
    jne LOOP_40
    cmp byte [backtrack_switch], 1
    je LA136
    jmp terminate_program
LOOP_40:
    print "cmp eax, 1"
    print 0x0A
    print '    '
    print "jne "
    call gn1
    print 0x0A
    print '    '
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_41
    cmp byte [backtrack_switch], 1
    je LA136
    jmp terminate_program
LOOP_41:
    error_store 'BODY'
    call vstack_clear
    call BODY
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_42
    cmp byte [backtrack_switch], 1
    je LA136
    jmp terminate_program
LOOP_42:
    print "jmp "
    call gn2
    print 0x0A
    print '    '
    call label
    call gn1
    print ":"
    print 0x0A
    print '    '
    error_store 'BODY'
    call vstack_clear
    call BODY
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_43
    cmp byte [backtrack_switch], 1
    je LA136
    jmp terminate_program
LOOP_43:
    call label
    call gn2
    print ":"
    print 0x0A
    print '    '
    
LA136:
    
LA140:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
ASMMACRO:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "asmmacro"
    cmp byte [eswitch], 1
    je LA141
    test_input_string "["
    cmp byte [eswitch], 1
    jne LOOP_44
    cmp byte [backtrack_switch], 1
    je LA141
    jmp terminate_program
LOOP_44:
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_45
    cmp byte [backtrack_switch], 1
    je LA141
    jmp terminate_program
LOOP_45:
    print "jmp "
    call gn1
    print 0x0A
    print '    '
    call label
    call copy_last_match
    print ":"
    print 0x0A
    print '    '
    print "push ebp"
    print 0x0A
    print '    '
    print "mov ebp, esp"
    print 0x0A
    print '    '
    
LA142:
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA143
    
LA143:
    
LA144:
    cmp byte [eswitch], 0
    je LA142
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_46
    cmp byte [backtrack_switch], 1
    je LA141
    jmp terminate_program
LOOP_46:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_47
    cmp byte [backtrack_switch], 1
    je LA141
    jmp terminate_program
LOOP_47:
    
LA145:
    error_store 'RAW'
    call vstack_clear
    call RAW
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA146
    call copy_last_match
    print 0x0A
    print '    '
    
LA146:
    
LA147:
    cmp byte [eswitch], 0
    je LA145
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_48
    cmp byte [backtrack_switch], 1
    je LA141
    jmp terminate_program
LOOP_48:
    print "mov esp, ebp"
    print 0x0A
    print '    '
    print "pop ebp"
    print 0x0A
    print '    '
    print "ret"
    print 0x0A
    print '    '
    call label
    call gn1
    print ":"
    print 0x0A
    print '    '
    
LA141:
    
LA148:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
ASM:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "asm"
    cmp byte [eswitch], 1
    je LA149
    error_store 'RAW'
    call vstack_clear
    call RAW
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_49
    cmp byte [backtrack_switch], 1
    je LA149
    jmp terminate_program
LOOP_49:
    call copy_last_match
    print 0x0A
    print '    '
    
LA149:
    
LA150:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
MOV:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "mov"
    cmp byte [eswitch], 1
    je LA151
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_50
    cmp byte [backtrack_switch], 1
    je LA151
    jmp terminate_program
LOOP_50:
    mov esi, last_match
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_51
    cmp byte [backtrack_switch], 1
    je LA151
    jmp terminate_program
LOOP_51:
    error_store 'SYMBOL_TABLE_ID'
    call vstack_clear
    call SYMBOL_TABLE_ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA152
    
LA152:
    cmp byte [eswitch], 0
    je LA153
    test_input_string "["
    cmp byte [eswitch], 1
    je LA154
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA155
    
LA155:
    cmp byte [eswitch], 0
    je LA156
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA157
    
LA157:
    
LA156:
    cmp byte [eswitch], 1
    jne LOOP_52
    cmp byte [backtrack_switch], 1
    je LA154
    jmp terminate_program
LOOP_52:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_53
    cmp byte [backtrack_switch], 1
    je LA154
    jmp terminate_program
LOOP_53:
    
LA154:
    
LA153:
    cmp byte [eswitch], 1
    je LA158
    print "mov "
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print ", eax"
    print 0x0A
    print '    '
    
LA158:
    cmp byte [eswitch], 0
    je LA159
    error_store 'NUMBER'
    call vstack_clear
    call NUMBER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA160
    print "mov "
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print ", "
    call copy_last_match
    print 0x0A
    print '    '
    
LA160:
    
LA159:
    cmp byte [eswitch], 1
    jne LOOP_54
    cmp byte [backtrack_switch], 1
    je LA151
    jmp terminate_program
LOOP_54:
    
LA151:
    
LA161:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
BUILTINS:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "syscall"
    cmp byte [eswitch], 1
    je LA162
    error_store 'NUMBER'
    call vstack_clear
    call NUMBER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_55
    cmp byte [backtrack_switch], 1
    je LA162
    jmp terminate_program
LOOP_55:
    print "int "
    call copy_last_match
    print 0x0A
    print '    '
    
LA162:
    
LA163:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
DEFINE:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "define"
    cmp byte [eswitch], 1
    je LA164
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_56
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_56:
    mov esi, last_match
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_57
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_57:
    mov esi, last_match
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_58
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_58:
    cmp byte [eswitch], 1
    jne LOOP_59
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_59:
    cmp byte [eswitch], 1
    jne LOOP_60
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_60:
    cmp byte [is_global], 1
    jne define_local
    cmp byte [eswitch], 1
    jne LOOP_61
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_61:
    cmp byte [eswitch], 1
    jne LOOP_62
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_62:
    mov edx, 0x80000000
    mov edi, symbol_table
    mov esi, last_match
    call hash_set
    jmp define_end
    define_local:
    mov edx, dword [fn_arg_num]
    mov edi, symbol_table
    mov esi, last_match
    call hash_set
    define_end:
    error_store 'NUMBER'
    call vstack_clear
    call NUMBER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA165
    error_store 'MOV_INTO'
    call vstack_clear
    call MOV_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_63
    cmp byte [backtrack_switch], 1
    je LA165
    jmp terminate_program
LOOP_63:
    call copy_last_match
    print " ; define "
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print 0x0A
    print '    '
    
LA165:
    
LA166:
    cmp byte [eswitch], 1
    je LA167
    
LA167:
    cmp byte [eswitch], 0
    je LA168
    error_store 'STRING'
    call vstack_clear
    call STRING
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA169
    call label
    print "section .data"
    print 0x0A
    print '    '
    call gn3
    print " db "
    call copy_last_match
    print ", 0x00"
    print 0x0A
    print '    '
    call label
    print "section .text"
    print 0x0A
    print '    '
    error_store 'MOV_INTO'
    call vstack_clear
    call MOV_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_64
    cmp byte [backtrack_switch], 1
    je LA169
    jmp terminate_program
LOOP_64:
    call gn3
    print " ; define "
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print 0x0A
    print '    '
    
LA169:
    
LA170:
    cmp byte [eswitch], 1
    je LA171
    
LA171:
    cmp byte [eswitch], 0
    je LA168
    error_store 'SYMBOL_TABLE_ID'
    call vstack_clear
    call SYMBOL_TABLE_ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA172
    error_store 'MOV_INTO'
    call vstack_clear
    call MOV_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_65
    cmp byte [backtrack_switch], 1
    je LA172
    jmp terminate_program
LOOP_65:
    print "eax ; define "
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print 0x0A
    print '    '
    
LA172:
    
LA173:
    cmp byte [eswitch], 1
    je LA174
    
LA174:
    cmp byte [eswitch], 0
    je LA168
    test_input_string "["
    cmp byte [eswitch], 1
    je LA175
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA176
    
LA176:
    cmp byte [eswitch], 0
    je LA177
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA178
    
LA178:
    
LA177:
    cmp byte [eswitch], 1
    jne LOOP_66
    cmp byte [backtrack_switch], 1
    je LA175
    jmp terminate_program
LOOP_66:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_67
    cmp byte [backtrack_switch], 1
    je LA175
    jmp terminate_program
LOOP_67:
    error_store 'MOV_INTO'
    call vstack_clear
    call MOV_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_68
    cmp byte [backtrack_switch], 1
    je LA175
    jmp terminate_program
LOOP_68:
    print "eax ; define "
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print 0x0A
    print '    '
    
LA175:
    
LA179:
    cmp byte [eswitch], 1
    je LA180
    
LA180:
    
LA168:
    cmp byte [eswitch], 1
    jne LOOP_69
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_69:
    cmp byte [eswitch], 1
    jne LOOP_70
    cmp byte [backtrack_switch], 1
    je LA164
    jmp terminate_program
LOOP_70:
    cmp byte [is_global], 1
    je no_sub
    dec dword [fn_arg_num]
    print "sub esp, 4"
    print 0x0A
    print '    '
    no_sub:
    
LA164:
    
LA181:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
MOV_INTO:
    push ebp
    mov ebp, esp
    push esi
    cmp byte [eswitch], 1
    je LA182
    cmp byte [is_global], 1
    jne mov_into_local
    cmp byte [eswitch], 1
    jne LOOP_71
    cmp byte [backtrack_switch], 1
    je LA182
    jmp terminate_program
LOOP_71:
    call label
    print "section .bss"
    print 0x0A
    print '    '
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print " resd 1"
    print 0x0A
    print '    '
    call label
    print "section .text"
    print 0x0A
    print '    '
    print "mov dword ["
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print "], "
    jmp mov_end
    mov_into_local:
    print "mov dword [ebp"
    cmp byte [eswitch], 1
    jne LOOP_72
    cmp byte [backtrack_switch], 1
    je LA182
    jmp terminate_program
LOOP_72:
    cmp byte [eswitch], 1
    jne LOOP_73
    cmp byte [backtrack_switch], 1
    je LA182
    jmp terminate_program
LOOP_73:
    mov eax, dword [fn_arg_num]
    cmp byte [eswitch], 1
    jne LOOP_74
    cmp byte [backtrack_switch], 1
    je LA182
    jmp terminate_program
LOOP_74:
    imul eax, eax, 4
    cmp byte [eswitch], 1
    jne LOOP_75
    cmp byte [backtrack_switch], 1
    je LA182
    jmp terminate_program
LOOP_75:
    add eax, 8
    cmp byte [eswitch], 1
    jne LOOP_76
    cmp byte [backtrack_switch], 1
    je LA182
    jmp terminate_program
LOOP_76:
    mov esi, eax
    mov edi, outbuff
    add edi, dword [outbuff_offset]
    call inttostrsigned
    add dword [outbuff_offset], eax
    print "], "
    mov_end:
    
LA182:
    
LA183:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
SET:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "set!"
    cmp byte [eswitch], 1
    je LA184
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_77
    cmp byte [backtrack_switch], 1
    je LA184
    jmp terminate_program
LOOP_77:
    
section .data
    LC1 db "", 0x00
    
section .text
    mov esi, LC1
    mov edi, last_match
    call strcat
    mov esi, eax
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_78
    cmp byte [backtrack_switch], 1
    je LA184
    jmp terminate_program
LOOP_78:
    
section .data
    LC2 db "", 0x00
    
section .text
    mov esi, LC2
    mov edi, last_match
    call strcat
    mov esi, eax
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_79
    cmp byte [backtrack_switch], 1
    je LA184
    jmp terminate_program
LOOP_79:
    error_store 'NUMBER'
    call vstack_clear
    call NUMBER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA185
    error_store 'SET_INTO'
    call vstack_clear
    call SET_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_80
    cmp byte [backtrack_switch], 1
    je LA185
    jmp terminate_program
LOOP_80:
    call copy_last_match
    print " ; set "
    print 0x0A
    print '    '
    
LA185:
    
LA186:
    cmp byte [eswitch], 1
    je LA187
    
LA187:
    cmp byte [eswitch], 0
    je LA188
    error_store 'STRING'
    call vstack_clear
    call STRING
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA189
    call label
    print "section .data"
    print 0x0A
    print '    '
    call gn3
    print " db "
    call copy_last_match
    print ", 0x00"
    print 0x0A
    print '    '
    call label
    print "section .text"
    print 0x0A
    print '    '
    error_store 'SET_INTO'
    call vstack_clear
    call SET_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_81
    cmp byte [backtrack_switch], 1
    je LA189
    jmp terminate_program
LOOP_81:
    call gn3
    print " ; set "
    print 0x0A
    print '    '
    
LA189:
    
LA190:
    cmp byte [eswitch], 1
    je LA191
    
LA191:
    cmp byte [eswitch], 0
    je LA188
    error_store 'SYMBOL_TABLE_ID'
    call vstack_clear
    call SYMBOL_TABLE_ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA192
    error_store 'SET_INTO'
    call vstack_clear
    call SET_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_82
    cmp byte [backtrack_switch], 1
    je LA192
    jmp terminate_program
LOOP_82:
    print "eax ; set "
    print 0x0A
    print '    '
    
LA192:
    
LA193:
    cmp byte [eswitch], 1
    je LA194
    
LA194:
    cmp byte [eswitch], 0
    je LA188
    test_input_string "["
    cmp byte [eswitch], 1
    je LA195
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA196
    
LA196:
    cmp byte [eswitch], 0
    je LA197
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA198
    
LA198:
    
LA197:
    cmp byte [eswitch], 1
    jne LOOP_83
    cmp byte [backtrack_switch], 1
    je LA195
    jmp terminate_program
LOOP_83:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_84
    cmp byte [backtrack_switch], 1
    je LA195
    jmp terminate_program
LOOP_84:
    error_store 'SET_INTO'
    call vstack_clear
    call SET_INTO
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_85
    cmp byte [backtrack_switch], 1
    je LA195
    jmp terminate_program
LOOP_85:
    print "eax ; set "
    print 0x0A
    print '    '
    
LA195:
    
LA199:
    cmp byte [eswitch], 1
    je LA200
    
LA200:
    
LA188:
    cmp byte [eswitch], 1
    jne LOOP_86
    cmp byte [backtrack_switch], 1
    je LA184
    jmp terminate_program
LOOP_86:
    
LA184:
    
LA201:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
SET_INTO:
    push ebp
    mov ebp, esp
    push esi
    mov edi, symbol_table
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    call hash_get
    cmp byte [eswitch], 1
    jne LOOP_87
    cmp byte [backtrack_switch], 1
    je LA202
    jmp terminate_program
LOOP_87:
    cmp byte [eswitch], 1
    jne LOOP_88
    cmp byte [backtrack_switch], 1
    je LA202
    jmp terminate_program
LOOP_88:
    cmp eax, 0x80000000
    jne set_into_local
    print "mov dword ["
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print "], "
    jmp set_into_end
    set_into_local:
    push eax
    print "mov dword [ebp"
    pop eax
    cmp byte [eswitch], 1
    jne LOOP_89
    cmp byte [backtrack_switch], 1
    je LA202
    jmp terminate_program
LOOP_89:
    cmp byte [eswitch], 1
    jne LOOP_90
    cmp byte [backtrack_switch], 1
    je LA202
    jmp terminate_program
LOOP_90:
    cmp byte [eswitch], 1
    jne LOOP_91
    cmp byte [backtrack_switch], 1
    je LA202
    jmp terminate_program
LOOP_91:
    imul eax, eax, 4
    cmp byte [eswitch], 1
    jne LOOP_92
    cmp byte [backtrack_switch], 1
    je LA202
    jmp terminate_program
LOOP_92:
    add eax, 8
    cmp byte [eswitch], 1
    jne LOOP_93
    cmp byte [backtrack_switch], 1
    je LA202
    jmp terminate_program
LOOP_93:
    mov esi, eax
    mov edi, outbuff
    add edi, dword [outbuff_offset]
    call inttostrsigned
    add dword [outbuff_offset], eax
    print "], "
    set_into_end:
    
LA202:
    
LA203:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
DEFUNC:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "defunc"
    cmp byte [eswitch], 1
    je LA204
    mov byte [is_global], 0
    test_input_string "["
    cmp byte [eswitch], 1
    jne LOOP_94
    cmp byte [backtrack_switch], 1
    je LA204
    jmp terminate_program
LOOP_94:
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_95
    cmp byte [backtrack_switch], 1
    je LA204
    jmp terminate_program
LOOP_95:
    print "jmp "
    call gn1
    print 0x0A
    print '    '
    call label
    call copy_last_match
    print ":"
    print 0x0A
    print '    '
    print "push ebp"
    print 0x0A
    print '    '
    print "mov ebp, esp"
    print 0x0A
    print '    '
    mov dword [fn_arg_num], 0
    
LA205:
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA206
    cmp byte [eswitch], 1
    jne LOOP_96
    cmp byte [backtrack_switch], 1
    je LA206
    jmp terminate_program
LOOP_96:
    cmp byte [eswitch], 1
    jne LOOP_97
    cmp byte [backtrack_switch], 1
    je LA206
    jmp terminate_program
LOOP_97:
    mov edx, dword [fn_arg_num]
    mov edi, symbol_table
    mov esi, last_match
    call hash_set
    inc dword [fn_arg_num]
    
LA206:
    
LA207:
    cmp byte [eswitch], 0
    je LA205
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_98
    cmp byte [backtrack_switch], 1
    je LA204
    jmp terminate_program
LOOP_98:
    cmp byte [eswitch], 1
    jne LOOP_99
    cmp byte [backtrack_switch], 1
    je LA204
    jmp terminate_program
LOOP_99:
    cmp byte [eswitch], 1
    jne LOOP_100
    cmp byte [backtrack_switch], 1
    je LA204
    jmp terminate_program
LOOP_100:
    mov dword [fn_arg_num], -3
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_101
    cmp byte [backtrack_switch], 1
    je LA204
    jmp terminate_program
LOOP_101:
    
LA208:
    error_store 'BODY'
    call vstack_clear
    call BODY
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA209
    
LA209:
    
LA210:
    cmp byte [eswitch], 0
    je LA208
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_102
    cmp byte [backtrack_switch], 1
    je LA204
    jmp terminate_program
LOOP_102:
    mov dword [fn_arg_num], 0
    print "mov esp, ebp"
    print 0x0A
    print '    '
    print "pop ebp"
    print 0x0A
    print '    '
    print "ret"
    print 0x0A
    print '    '
    call label
    call gn1
    print ":"
    print 0x0A
    print '    '
    mov byte [is_global], 1
    
LA204:
    
LA211:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
FUNC_CALL:
    push ebp
    mov ebp, esp
    push esi
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA212
    mov esi, last_match
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_103
    cmp byte [backtrack_switch], 1
    je LA212
    jmp terminate_program
LOOP_103:
    mov dword [used_arg_count], 0
    error_store 'CALL_ARGS'
    call vstack_clear
    call CALL_ARGS
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    jne LOOP_104
    cmp byte [backtrack_switch], 1
    je LA212
    jmp terminate_program
LOOP_104:
    print "call "
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print 0x0A
    print '    '
    cmp byte [eswitch], 1
    jne LOOP_105
    cmp byte [backtrack_switch], 1
    je LA212
    jmp terminate_program
LOOP_105:
    mov ebx, dword [used_arg_count]
    imul ebx, ebx, 4
    print "add esp, "
    mov esi, ebx
    mov edi, outbuff
    add edi, dword [outbuff_offset]
    call inttostr
    add dword [outbuff_offset], eax
    mov dword [used_arg_count], 0
    print 0x0A
    print '    '
    print "push eax"
    print 0x0A
    print '    '
    
LA212:
    
LA213:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
CALL_ARGS:
    push ebp
    mov ebp, esp
    push esi
    
LA214:
    error_store 'NUMBER'
    call vstack_clear
    call NUMBER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA215
    
section .data
    LC3 db "push ", 0x00
    
section .text
    mov esi, LC3
    mov edi, last_match
    call strcat
    mov esi, eax
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_106
    cmp byte [backtrack_switch], 1
    je LA215
    jmp terminate_program
LOOP_106:
    
LA215:
    cmp byte [eswitch], 0
    je LA216
    test_input_string "["
    cmp byte [eswitch], 1
    je LA217
    push dword [used_arg_count]
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA218
    
LA218:
    cmp byte [eswitch], 0
    je LA219
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA220
    
LA220:
    
LA219:
    cmp byte [eswitch], 1
    jne LOOP_107
    cmp byte [backtrack_switch], 1
    je LA217
    jmp terminate_program
LOOP_107:
    pop dword [used_arg_count]
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_108
    cmp byte [backtrack_switch], 1
    je LA217
    jmp terminate_program
LOOP_108:
    
section .data
    LC4 db "", 0x00
    
section .text
    mov esi, LC4
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_109
    cmp byte [backtrack_switch], 1
    je LA217
    jmp terminate_program
LOOP_109:
    
LA217:
    cmp byte [eswitch], 0
    je LA216
    error_store 'SYMBOL_TABLE_PUSH_BUFFER'
    call vstack_clear
    call SYMBOL_TABLE_PUSH_BUFFER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA221
    
LA221:
    cmp byte [eswitch], 0
    je LA216
    error_store 'STRING_ARG'
    call vstack_clear
    call STRING_ARG
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA222
    
LA222:
    
LA216:
    cmp byte [eswitch], 1
    je LA223
    inc dword [used_arg_count]
    
LA223:
    
LA224:
    cmp byte [eswitch], 0
    je LA214
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA225
    mov ecx, dword [used_arg_count]
    loop_pop_args:
    cmp ecx, 0
    je loop_pop_args_end
    push ecx
    mov esi, str_vector_8192
    call vector_pop_string
    mov esi, eax
    mov edi, outbuff
    add edi, [outbuff_offset]
    call strcpy
    add dword [outbuff_offset], eax
    print 0x0A
    print '    '
    pop ecx
    dec ecx
    jmp loop_pop_args
    loop_pop_args_end:
    
LA225:
    
LA226:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
SYMBOL_TABLE_PUSH_BUFFER:
    push ebp
    mov ebp, esp
    push esi
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA227
    mov edi, symbol_table
    mov esi, last_match
    call hash_get
    cmp byte [eswitch], 1
    jne LOOP_110
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_110:
    cmp byte [eswitch], 1
    jne LOOP_111
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_111:
    cmp eax, 0x80000000
    jne stpb_local
    mov esi, push_prefix_global
    mov edi, push_buffer
    call strcpy
    mov esi, last_match
    mov edi, push_buffer
    add edi, 12
    call strcpy
    mov edi, push_buffer
    add edi, 12
    mov byte [edi+eax], ']'
    mov byte [edi+eax+1], 0x00
    mov esi, push_buffer
    mov edi, str_vector_8192
    call vector_push_string_mm32
    jmp stpb_end
    stpb_local:
    cmp byte [eswitch], 1
    jne LOOP_112
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_112:
    cmp byte [eswitch], 1
    jne LOOP_113
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_113:
    cmp byte [eswitch], 1
    jne LOOP_114
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_114:
    push eax
    mov esi, push_prefix
    mov edi, push_buffer
    call strcpy
    pop eax
    imul eax, eax, 4
    cmp byte [eswitch], 1
    jne LOOP_115
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_115:
    add eax, 8
    cmp byte [eswitch], 1
    jne LOOP_116
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_116:
    mov esi, eax
    cmp byte [eswitch], 1
    jne LOOP_117
    cmp byte [backtrack_switch], 1
    je LA227
    jmp terminate_program
LOOP_117:
    mov edi, push_buffer
    add edi, 15
    call inttostrsigned
    mov edi, push_buffer
    add edi, 15
    mov byte [edi+eax], ']'
    mov byte [edi+eax+1], 0x00
    mov esi, push_buffer
    mov edi, str_vector_8192
    call vector_push_string_mm32
    stpb_end:
    
LA227:
    
LA228:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
STRING_ARG:
    push ebp
    mov ebp, esp
    push esi
    error_store 'STRING'
    call vstack_clear
    call STRING
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA229
    call label
    print "section .data"
    print 0x0A
    print '    '
    call gn3
    print " db "
    call copy_last_match
    print ", 0x00"
    print 0x0A
    print '    '
    call label
    print "section .text"
    print 0x0A
    print '    '
    
section .data
    LC5 db "", 0x00
    
section .text
    mov esi, LC5
    mov edi, str_vector_8192
    call vector_push_string_mm32
    cmp byte [eswitch], 1
    jne LOOP_118
    cmp byte [backtrack_switch], 1
    je LA229
    jmp terminate_program
LOOP_118:
    cmp byte [eswitch], 1
    jne LOOP_119
    cmp byte [backtrack_switch], 1
    je LA229
    jmp terminate_program
LOOP_119:
    print "push "
    call gn3
    print 0x0A
    print '    '
    
LA229:
    
LA230:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
BINOP_ARGS:
    push ebp
    mov ebp, esp
    push esi
    
LA231:
    error_store 'NUMBER'
    call vstack_clear
    call NUMBER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA232
    print "push "
    call copy_last_match
    print 0x0A
    print '    '
    
LA232:
    cmp byte [eswitch], 0
    je LA233
    test_input_string "["
    cmp byte [eswitch], 1
    je LA234
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA235
    
LA235:
    cmp byte [eswitch], 0
    je LA236
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA237
    
LA237:
    
LA236:
    cmp byte [eswitch], 1
    jne LOOP_120
    cmp byte [backtrack_switch], 1
    je LA234
    jmp terminate_program
LOOP_120:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_121
    cmp byte [backtrack_switch], 1
    je LA234
    jmp terminate_program
LOOP_121:
    
LA234:
    
LA238:
    cmp byte [eswitch], 1
    je LA239
    
LA239:
    cmp byte [eswitch], 0
    je LA233
    error_store 'SYMBOL_TABLE_PUSH'
    call vstack_clear
    call SYMBOL_TABLE_PUSH
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA240
    
LA240:
    
LA233:
    cmp byte [eswitch], 1
    je LA241
    
LA242:
    error_store 'NUMBER'
    call vstack_clear
    call NUMBER
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA243
    print "push "
    call copy_last_match
    print 0x0A
    print '    '
    
LA243:
    cmp byte [eswitch], 0
    je LA244
    test_input_string "["
    cmp byte [eswitch], 1
    je LA245
    error_store 'FUNC_CALL'
    call vstack_clear
    call FUNC_CALL
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA246
    
LA246:
    cmp byte [eswitch], 0
    je LA247
    error_store 'ARITHMETIC'
    call vstack_clear
    call ARITHMETIC
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA248
    
LA248:
    
LA247:
    cmp byte [eswitch], 1
    jne LOOP_122
    cmp byte [backtrack_switch], 1
    je LA245
    jmp terminate_program
LOOP_122:
    test_input_string "]"
    cmp byte [eswitch], 1
    jne LOOP_123
    cmp byte [backtrack_switch], 1
    je LA245
    jmp terminate_program
LOOP_123:
    
LA245:
    
LA249:
    cmp byte [eswitch], 1
    je LA250
    
LA250:
    cmp byte [eswitch], 0
    je LA244
    error_store 'SYMBOL_TABLE_PUSH'
    call vstack_clear
    call SYMBOL_TABLE_PUSH
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA251
    
LA251:
    
LA244:
    cmp byte [eswitch], 1
    je LA252
    print "pop ebx"
    print 0x0A
    print '    '
    
LA252:
    
LA253:
    cmp byte [eswitch], 0
    je LA242
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    jne LOOP_124
    cmp byte [backtrack_switch], 1
    je LA241
    jmp terminate_program
LOOP_124:
    print "pop eax"
    print 0x0A
    print '    '
    
LA241:
    
LA254:
    cmp byte [eswitch], 0
    je LA231
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA255
    
LA255:
    
LA256:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
SYMBOL_TABLE_PUSH:
    push ebp
    mov ebp, esp
    push esi
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA257
    mov edi, symbol_table
    mov esi, last_match
    call hash_get
    cmp byte [eswitch], 1
    jne LOOP_125
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_125:
    cmp byte [eswitch], 1
    jne LOOP_126
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_126:
    cmp eax, 0x80000000
    jne stp_local
    print "push dword ["
    call copy_last_match
    print "]"
    print 0x0A
    print '    '
    jmp stp_end
    stp_local:
    cmp byte [eswitch], 1
    jne LOOP_127
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_127:
    cmp byte [eswitch], 1
    jne LOOP_128
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_128:
    cmp byte [eswitch], 1
    jne LOOP_129
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_129:
    push eax
    print "push dword [ebp"
    pop eax
    imul eax, eax, 4
    cmp byte [eswitch], 1
    jne LOOP_130
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_130:
    add eax, 8
    cmp byte [eswitch], 1
    jne LOOP_131
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_131:
    mov esi, eax
    cmp byte [eswitch], 1
    jne LOOP_132
    cmp byte [backtrack_switch], 1
    je LA257
    jmp terminate_program
LOOP_132:
    mov edi, outbuff
    add edi, dword [outbuff_offset]
    call inttostrsigned
    add dword [outbuff_offset], eax
    print "] ; get "
    call copy_last_match
    print 0x0A
    print '    '
    stp_end:
    
LA257:
    
LA258:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
SYMBOL_TABLE_ID:
    push ebp
    mov ebp, esp
    push esi
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA259
    mov edi, symbol_table
    mov esi, last_match
    call hash_get
    cmp byte [eswitch], 1
    jne LOOP_133
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_133:
    cmp byte [eswitch], 1
    jne LOOP_134
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_134:
    cmp eax, 0x80000000
    jne st_local
    print "mov eax, dword ["
    call copy_last_match
    print "]"
    print 0x0A
    print '    '
    jmp st_end
    st_local:
    cmp byte [eswitch], 1
    jne LOOP_135
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_135:
    cmp byte [eswitch], 1
    jne LOOP_136
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_136:
    cmp byte [eswitch], 1
    jne LOOP_137
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_137:
    push eax
    print "mov eax, dword [ebp"
    pop eax
    imul eax, eax, 4
    cmp byte [eswitch], 1
    jne LOOP_138
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_138:
    add eax, 8
    cmp byte [eswitch], 1
    jne LOOP_139
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_139:
    mov esi, eax
    cmp byte [eswitch], 1
    jne LOOP_140
    cmp byte [backtrack_switch], 1
    je LA259
    jmp terminate_program
LOOP_140:
    mov edi, outbuff
    add edi, dword [outbuff_offset]
    call inttostrsigned
    add dword [outbuff_offset], eax
    print "] ; get "
    call copy_last_match
    print 0x0A
    print '    '
    st_end:
    
LA259:
    
LA260:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
SYMBOL_TABLE_ID_EBX:
    push ebp
    mov ebp, esp
    push esi
    error_store 'ID'
    call vstack_clear
    call ID
    call vstack_restore
    call error_clear
    cmp byte [eswitch], 1
    je LA261
    mov edi, symbol_table
    mov esi, last_match
    call hash_get
    cmp byte [eswitch], 1
    jne LOOP_141
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_141:
    cmp byte [eswitch], 1
    jne LOOP_142
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_142:
    cmp eax, 0x80000000
    jne st_ebx_local
    print "mov ebx, dword ["
    call copy_last_match
    print "]"
    print 0x0A
    print '    '
    jmp st_ebx_end
    st_ebx_local:
    cmp byte [eswitch], 1
    jne LOOP_143
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_143:
    cmp byte [eswitch], 1
    jne LOOP_144
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_144:
    cmp byte [eswitch], 1
    jne LOOP_145
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_145:
    push eax
    print "mov ebx, dword [ebp"
    pop eax
    imul eax, eax, 4
    cmp byte [eswitch], 1
    jne LOOP_146
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_146:
    add eax, 8
    cmp byte [eswitch], 1
    jne LOOP_147
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_147:
    mov esi, eax
    cmp byte [eswitch], 1
    jne LOOP_148
    cmp byte [backtrack_switch], 1
    je LA261
    jmp terminate_program
LOOP_148:
    mov edi, outbuff
    add edi, dword [outbuff_offset]
    call inttostrsigned
    add dword [outbuff_offset], eax
    print "] ; get "
    call copy_last_match
    print 0x0A
    print '    '
    st_ebx_end:
    
LA261:
    
LA262:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
COMMENT:
    push ebp
    mov ebp, esp
    push esi
    test_input_string "//"
    cmp byte [eswitch], 1
    je LA263
    match_not 10
    cmp byte [eswitch], 1
    jne LOOP_149
    cmp byte [backtrack_switch], 1
    je LA263
    jmp terminate_program
LOOP_149:
    
LA263:
    
LA264:
    pop esi
    mov esp, ebp
    pop ebp
    ret
    
; -- Tokens --
    
PREFIX:
    
LA265:
    mov edi, 32
    call test_char_equal
    cmp byte [eswitch], 0
    je LA266
    mov edi, 9
    call test_char_equal
    cmp byte [eswitch], 0
    je LA266
    mov edi, 13
    call test_char_equal
    cmp byte [eswitch], 0
    je LA266
    mov edi, 10
    call test_char_equal
    
LA266:
    call scan_or_parse
    cmp byte [eswitch], 0
    je LA265
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA267
    
LA267:
    
LA268:
    ret
    
NUMBER:
    call PREFIX
    cmp byte [eswitch], 1
    je LA269
    mov byte [tflag], 1
    call clear_token
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA269
    call DIGIT
    cmp byte [eswitch], 1
    je LA269
    
LA270:
    call DIGIT
    cmp byte [eswitch], 0
    je LA270
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA269
    mov byte [tflag], 0
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA269
    
LA269:
    
LA271:
    ret
    
DIGIT:
    mov edi, 48
    call test_char_greater_equal
    cmp byte [eswitch], 0
    jne LA272
    mov edi, 57
    call test_char_less_equal
    
LA272:
    
LA273:
    call scan_or_parse
    cmp byte [eswitch], 1
    je LA274
    
LA274:
    
LA275:
    ret
    
ID:
    call PREFIX
    cmp byte [eswitch], 1
    je LA276
    mov byte [tflag], 1
    call clear_token
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA276
    call ALPHA
    cmp byte [eswitch], 1
    je LA276
    
LA277:
    call ALPHA
    cmp byte [eswitch], 1
    je LA278
    
LA278:
    cmp byte [eswitch], 0
    je LA279
    call DIGIT
    cmp byte [eswitch], 1
    je LA280
    
LA280:
    
LA279:
    cmp byte [eswitch], 0
    je LA277
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA276
    mov byte [tflag], 0
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA276
    
LA276:
    
LA281:
    ret
    
ALPHA:
    mov edi, 65
    call test_char_greater_equal
    cmp byte [eswitch], 0
    jne LA282
    mov edi, 90
    call test_char_less_equal
    
LA282:
    cmp byte [eswitch], 0
    je LA283
    mov edi, 95
    call test_char_equal
    cmp byte [eswitch], 0
    je LA283
    mov edi, 97
    call test_char_greater_equal
    cmp byte [eswitch], 0
    jne LA284
    mov edi, 122
    call test_char_less_equal
    
LA284:
    
LA283:
    call scan_or_parse
    cmp byte [eswitch], 1
    je LA285
    
LA285:
    
LA286:
    ret
    
STRING:
    call PREFIX
    cmp byte [eswitch], 1
    je LA287
    mov byte [tflag], 1
    call clear_token
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA287
    mov edi, 34
    call test_char_equal
    
LA288:
    call scan_or_parse
    cmp byte [eswitch], 1
    je LA287
    
LA289:
    mov edi, 13
    call test_char_equal
    cmp byte [eswitch], 0
    je LA290
    mov edi, 10
    call test_char_equal
    cmp byte [eswitch], 0
    je LA290
    mov edi, 34
    call test_char_equal
    
LA290:
    mov al, byte [eswitch]
    xor al, 1
    mov byte [eswitch], al
    call scan_or_parse
    cmp byte [eswitch], 0
    je LA289
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA287
    mov edi, 34
    call test_char_equal
    
LA291:
    call scan_or_parse
    cmp byte [eswitch], 1
    je LA287
    mov byte [tflag], 0
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA287
    
LA287:
    
LA292:
    ret
    
RAW:
    call PREFIX
    cmp byte [eswitch], 1
    je LA293
    mov edi, 34
    call test_char_equal
    
LA294:
    call scan_or_parse
    cmp byte [eswitch], 1
    je LA293
    mov byte [tflag], 1
    call clear_token
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA293
    
LA295:
    mov edi, 13
    call test_char_equal
    cmp byte [eswitch], 0
    je LA296
    mov edi, 10
    call test_char_equal
    cmp byte [eswitch], 0
    je LA296
    mov edi, 34
    call test_char_equal
    
LA296:
    mov al, byte [eswitch]
    xor al, 1
    mov byte [eswitch], al
    call scan_or_parse
    cmp byte [eswitch], 0
    je LA295
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA293
    mov byte [tflag], 0
    mov byte [eswitch], 0
    cmp byte [eswitch], 1
    je LA293
    mov edi, 34
    call test_char_equal
    
LA297:
    call scan_or_parse
    cmp byte [eswitch], 1
    je LA293
    
LA293:
    
LA298:
    ret
    
