
section .text
    global _start
    
_start:
    push ebp
    mov ebp, esp
    ; starting ROOT_BODY
    jmp LA1
    
derefb:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov eax, [ebp+8]
    ; generated by ASM
    ; starting BODY
    mov bl, byte [eax]
    ; generated by ASM
    ; starting BODY
    xor eax, eax
    ; generated by ASM
    ; starting BODY
    mov al, bl
    ; generated by ASM
    mov esp, ebp
    pop ebp
    ret
    
LA1:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA2
    
write:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov eax, 4
    ; generated by ASM
    ; starting BODY
    mov ebx, [ebp+8]
    ; generated by ASM
    ; starting BODY
    mov ecx, [ebp+12]
    ; generated by ASM
    ; starting BODY
    mov edx, [ebp+16]
    ; generated by ASM
    ; starting BODY
    int 128
    ; generated by BUILTINS
    mov esp, ebp
    pop ebp
    ret
    
LA2:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA3
    
exit:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov eax, 1
    ; generated by ASM
    ; starting BODY
    mov ebx, [ebp+8]
    ; generated by ASM
    ; starting BODY
    int 128
    ; generated by BUILTINS
    mov esp, ebp
    pop ebp
    ret
    
LA3:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA4
    
strlen:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov dword [ebp-4], 0 ; define len
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    
LB1:
    push dword [ebp+8] ; get s
    push dword [ebp-4] ; get len
    pop ebx
    pop eax
    add eax, ebx
    push eax
    call derefb
    add esp, 4
    push eax
    push 0
    pop ebx
    pop eax
    cmp eax, ebx
    mov eax, 0
    setne al
    cmp eax, 1
    jne LA5
    ; starting BODY
    push dword [ebp-4] ; get len
    push 1
    pop ebx
    pop eax
    add eax, ebx
    mov dword [ebp-4], eax ; set 
    ; generated by SET
    jmp LB1
    
LA5:
    ; generated by WHILE
    ; starting BODY
    push dword [ebp-4] ; get len
    pop eax
    mov esp, ebp
    pop ebp
    ret
    ; generated by RETURN
    mov esp, ebp
    pop ebp
    ret
    
LA4:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA6
    
fopen:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov eax, 5
    ; generated by ASM
    ; starting BODY
    mov ebx, [ebp+8]
    ; generated by ASM
    ; starting BODY
    mov ecx, [ebp+12]
    ; generated by ASM
    ; starting BODY
    int 128
    ; generated by BUILTINS
    mov esp, ebp
    pop ebp
    ret
    
LA6:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA7
    
fclose:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov eax, 6
    ; generated by ASM
    ; starting BODY
    mov ebx, [ebp+8]
    ; generated by ASM
    ; starting BODY
    int 128
    ; generated by BUILTINS
    mov esp, ebp
    pop ebp
    ret
    
LA7:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA8
    
fwrite:
    push ebp
    mov ebp, esp
    ; starting BODY
    push dword [ebp+12] ; get size
    push dword [ebp+16] ; get nmemb
    pop ebx
    pop eax
    imul eax, ebx
    mov dword [ebp-4], eax ; define writesize
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    mov eax, 4
    ; generated by ASM
    ; starting BODY
    mov ebx, [ebp+20]
    ; generated by ASM
    ; starting BODY
    mov ecx, [ebp+8]
    ; generated by ASM
    ; starting BODY
    mov edx, [ebp-4]
    ; generated by ASM
    ; starting BODY
    int 128
    ; generated by BUILTINS
    mov esp, ebp
    pop ebp
    ret
    
LA8:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA9
    
fread:
    push ebp
    mov ebp, esp
    ; starting BODY
    push dword [ebp+12] ; get size
    push dword [ebp+16] ; get nmemb
    pop ebx
    pop eax
    imul eax, ebx
    mov dword [ebp-4], eax ; define readsize
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    mov eax, 3
    ; generated by ASM
    ; starting BODY
    mov ebx, [ebp+20]
    ; generated by ASM
    ; starting BODY
    mov ecx, [ebp+8]
    ; generated by ASM
    ; starting BODY
    mov edx, [ebp-4]
    ; generated by ASM
    ; starting BODY
    int 128
    ; generated by BUILTINS
    mov esp, ebp
    pop ebp
    ret
    
LA9:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA10
    
memset:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov dword [ebp-4], 0 ; define set
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    mov dword [ebp-8], 0 ; define memptr
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    
LB2:
    push dword [ebp-4] ; get set
    push dword [ebp+16] ; get num
    pop ebx
    pop eax
    cmp eax, ebx
    mov eax, 0
    setne al
    cmp eax, 1
    jne LA11
    ; starting BODY
    push dword [ebp+8] ; get ptr
    push dword [ebp-4] ; get set
    pop ebx
    pop eax
    add eax, ebx
    push eax
    call derefb
    add esp, 4
    mov dword [ebp-8], eax ; set 
    ; generated by SET
    ; starting BODY
    mov eax, [ebp+12]
    ; generated by ASM
    ; starting BODY
    mov byte [ebp-8], al
    ; generated by ASM
    ; starting BODY
    push dword [ebp-4] ; get set
    push 1
    pop ebx
    pop eax
    add eax, ebx
    mov dword [ebp-4], eax ; set 
    ; generated by SET
    jmp LB2
    
LA11:
    ; generated by WHILE
    ; starting BODY
    push dword [ebp+8] ; get ptr
    pop eax
    mov esp, ebp
    pop ebp
    ret
    ; generated by RETURN
    mov esp, ebp
    pop ebp
    ret
    
LA10:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA12
    
memcpy:
    push ebp
    mov ebp, esp
    ; starting BODY
    mov dword [ebp-4], 0 ; define copied
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    mov dword [ebp-8], 0 ; define memptr
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    mov dword [ebp-12], 0 ; define value
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    
LB3:
    push dword [ebp-4] ; get copied
    push dword [ebp+16] ; get num
    pop ebx
    pop eax
    cmp eax, ebx
    mov eax, 0
    setne al
    cmp eax, 1
    jne LA13
    ; starting BODY
    push dword [ebp+8] ; get destination
    push dword [ebp-4] ; get copied
    pop ebx
    pop eax
    add eax, ebx
    push eax
    call derefb
    add esp, 4
    mov dword [ebp-8], eax ; set 
    ; generated by SET
    ; starting BODY
    push dword [ebp+12] ; get source
    push dword [ebp-4] ; get copied
    pop ebx
    pop eax
    add eax, ebx
    push eax
    call derefb
    add esp, 4
    mov dword [ebp-12], eax ; set 
    ; generated by SET
    ; starting BODY
    mov eax, [ebp-12]
    ; generated by ASM
    ; starting BODY
    mov byte [ebp-8], al
    ; generated by ASM
    ; starting BODY
    push dword [ebp-4] ; get copied
    push 1
    pop ebx
    pop eax
    add eax, ebx
    mov dword [ebp-4], eax ; set 
    ; generated by SET
    jmp LB3
    
LA13:
    ; generated by WHILE
    ; starting BODY
    push dword [ebp+8] ; get destination
    pop eax
    mov esp, ebp
    pop ebp
    ret
    ; generated by RETURN
    mov esp, ebp
    pop ebp
    ret
    
LA12:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    jmp LA14
    
main:
    push ebp
    mov ebp, esp
    ; starting BODY
    
section .data
    LC1 db "test.txt", 0x00
    
section .text
    push 2
    push LC1
    call fopen
    add esp, 8
    mov dword [ebp-4], eax ; define fd
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    
section .bss
    LC2 resb 1024
    
section .text
    mov eax, LC2
    mov dword [ebp-8], eax ; define buf
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    push dword [ebp-4]
    push 1024
    push 1
    push dword [ebp-8]
    call fread
    add esp, 16
    mov dword [ebp-12], eax ; define readsize
    sub esp, 4
    ; generated by DEFINE
    ; starting BODY
    push dword [ebp-12]
    push dword [ebp-8]
    push 1
    call write
    add esp, 12
    ; generated by FUNC_CALL
    ; starting BODY
    
section .data
    LC3 db "Hello, World!\n", 0x00
    
section .text
    push dword [ebp-4]
    push 13
    push 1
    push LC3
    call fwrite
    add esp, 16
    ; generated by FUNC_CALL
    ; starting BODY
    push dword [ebp-4]
    call fclose
    add esp, 4
    ; generated by FUNC_CALL
    ; starting BODY
    push 0
    call exit
    add esp, 4
    ; generated by FUNC_CALL
    mov esp, ebp
    pop ebp
    ret
    
LA14:
    ; generated by DEFUNC
    ; starting ROOT_BODY
    call main
    add esp, 0
    ; generated by FUNC_CALL
    mov esp, ebp
    pop ebp
    mov ebx, eax
    mov eax, 1
    int 0x80
    