on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: CI
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nasm and binutils
        run: |
          apt update
          apt install -y nasm
          apt install -y binutils
      - name: Run Tests
        run: bash ./tests/test.bash > tests/results.txt\
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tests/results.txt
            tests/tmp/**/diff.txt
  
  benchmark:
    needs:
      - test
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: apt update && apt install -y wget && apt install -y dpkg
      - run: wget https://github.com/sharkdp/hyperfine/releases/download/v1.16.1/hyperfine_1.16.1_amd64.deb
      - run: dpkg -i hyperfine_1.16.1_amd64.deb
      - run: bash benchmarks/*.bench.bash

      - uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmarks/results/